name: Bug Report
description: Submit a bug
title: "Bug: <Title>"
labels: ["Bug"]
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: Describe the bug that had occurred
      placeholder: Please be as concise and descriptive as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the Bug
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Platform
      description: What platform are you on?
      options:
        - Windows
        - Mac
        - Linux
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Desktop or Laptop?
      description: Were you on a Desktop or Laptop when this happened?
      options:
        - Desktop
        - Laptop
    validations:
      required: true
  - type: dropdown
    attributes:
      label: If Laptop, was your laptop plugged in?
      description: Was the laptop plugged in when the bug occurred?
      options:
        - Yes
        - No
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Editor or Build?
      description: Did this bug occur in the editor or in a build of the game?
      options:
        - Editor
        - Build
        - Both
    validations:
      required: true
